
spring:
  application:
    name: springcloud-zuul
  cloud:
    consul:
        host: localhost
        port: 8500
        discovery:
          instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
          service-name: springcloud-zuul
    config:
      discovery:
        enabled: true
        service-id: springcloud-config-server
      fail-fast: true
      username: root
      password: booszy
      profile: csdn
zuul:
  routes:
    springcloud-consumer-config: /consumer/**
    springcloud-provider-config: /provider/**
server:
  port: 8400