server:
  port: 8888
spring:
  application:
    name: springcloud-config-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    config:
      server:
        git:
          uri: https://git.coding.net/yirenyishi/springcloud-config-profile
          searchPaths: '{application}'

  security:
    basic:
      enabled: true
    user:
      name: root
      password: booszy